main: me.M0dii.EnhancedEnchant.EnhancedEnchant
name: EnhancedEnchantments
author: M0dii
version: 1.5
api-version: 1.16
depend:
  - mcMMO
commands:
  enhancedenchant:
    permission: enhancedenchant.command.enchant
    description: Enchant command.
    aliases: [ee, ae]
  unenchant:
    permission: enhancedenchant.command.unenchant
    description: Unenchant command.
    aliases: [unench, unen, ue]